all : stackt.c fun_stack.c
	gcc stackt.c fun_stack.c -o test_s
test : stackt.c fun_stack.c
	gcc stackt.c fun_stack.c -o test_s
	./test_s 1 nowy 2 plik
	./test_s 4 to 2 zdanie 7 jest 1 napisane 0 od 4 konca
	./test_s 69 analizator 3 pod 2 strukture 1 na 5 wzgledu 8 ze 0 potrzebne 3 sa 10 cyfry 5 te

